---
title: "Court of Public Opinion: A Sentiment Analysis"
subtitle: "Reddit’s collective reaction to Freddie Kitchens, Kevin Stefanski, and other recent NFL head coaching hires"
author: "Clay Girdner"
date: "2/14/2020"
output: html_document
---

Hand up, this time last year I thought Freddie Kitchens was a good hire for the Browns. The strong offensive finish to 2018 combined with Freddie’s seemingly close ties to Baker had me convinced that Kitchens was the man for the job. And I wasn’t about to let the fact that Freddie lacked any head coaching experience come between me and my delusions of Browns grandeur. I was hooked on recency bias, and it was a hell of a drug.

Fast forward to the present day. Freddie’s a goner, the Browns are once again riding the coaching carousel, and my hope-fueled dopamine high has long since faded. However, being so completely wrong left this armchair G.M.’s ego bruised and battered. I had to wonder if everyone else bought into the hype or if I was among a gullible minority who fell for Freddie’s good ole boy schtick? 

To answer this question, I set out to measure the consensus fan opinion of the Kitchens pick and then compare it to that of Kevin Stefanski and other recent NFL head coach selections. I would need a data source to conduct this experiment, so I turned to Reddit threads – specifically posts linking to a Tweet or team release announcing a new hiring as these threads produce large text samples and provide a consistent/similar population of commenters to conduct a sentiment analysis. 

I used Python to gather the comments for each of these threads, specifically the PRAW library which allows you to tap into Reddit's free API (see reddit_hire_data_pull.py in the repository for the code - https://github.com/ClayGirdner/nfl_hires_reddit_sentiment). 

In order to measure the overall sentiment for each thread, comments were fed through two different text analysis tools housed in Python – [VADER](http://comp.social.gatech.edu/papers/icwsm14.vader.hutto.pdf) and [TextBlob](https://textblob.readthedocs.io/en/dev/), both of which produce numeric scores indicating the degree of polarity for each comment (i.e. level of positivity/negativity). Two example comments and their resulting scores are provided below.

```{python polarity, echo=FALSE}
import pandas as pd
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

vader = SentimentIntensityAnalyzer()

comment_1 = 'I really like this hire for our team!'
comment_2 = 'This guy stinks! Why would we hire him?'

table = pd.DataFrame()

for comment in [comment_1, comment_2]:
    vader_polarity = vader.polarity_scores(comment)['compound']
    blob_polarity = TextBlob(comment).sentiment.polarity
    table.append({'Comment': comment, 'VADER': vader_polarity, 'TextBlob': blob_polarity}, ignore_index = True)
```






```{r libraries, include=FALSE}
library(nflscrapR)
library(tidyverse)
library(tidytext)
library(dplyr)
library(ggplot2)
library(ggimage)
library(ggrepel)
library(ggpubr)
library(stringr)
library(wordcloud2)
library(htmlwidgets)
library(webshot)

source("theme_pff.R")
```
